### ISSUE TITLE
Running tests under Mono on OS X

### ISSUE THREAD

**Issue by wilcoxjay** [Microsoft/dafny#101]
Executing tests (using `Test/runTests.py`) on OS X under mono uncovers several failing tests, which I believe are due to various cross-platform issues.

I am not sure whether OS X is intended to be a supported development platform or not, but I thought I would document my progress getting the tests to run here.

Please also see the companion branch [wilcoxjay/dafny/osx-fix-tests](https://github.com/wilcoxjay/dafny/tree/osx-fix-tests), which is a work in progress in addressing some of these issues.

- [x] `runTests.py`'s function `get_server_path` uses Windows-specific file name conventions and thus fails to find the server executable on OS X. This originally caused the script to crash. I have temporarily patched it not to crash. Additionally, it would be nice to to add a `--server` flag to the script to allow the user to manually specify where the server executable lives.
- [x] `Test/dafny0/SeqFromArray.dfy` fails on OS X under Mono due to an unexpected unreachable code warning. I fixed this by passing an additional `/noWarn` flag to the C# copiler, which ignores this warning globally, but that may be overkill.
- [x] `Test/dafny0/Extern.dfy` crashes Dafny with a `FileNotFound` exception because the `RUN` comment at the top of the test uses the Windows-specific path separator, which causes OS X to look for a file whose name contains a backslash. One possible fix would be to add another substitution to `runTests.py` that converted path separators. If that's too hacky, I'm open to other suggestions.

~There are 4 other failing tests in `Test/dafny0` that I haven't investigated yet.~ (UPDATE: these were spurious failures due to `runTest.py` diverging from `lit`.) But I wanted to see whether these kinds of problems are considered worth fixing before I get too far into it.

**Comment by cpitclaudel** [comment]
We're very happy to get this kind of issues fixed.  I ran the original test suite on Windows and GNU/Linux when I wrote the test driver 2 years ago, but I can see how it would have suffered a bit of bitrot since then :)

I'm not sure about how to fix extern.dfy.  Re server executable, I'm not sure I understand the issue: where is the script using Windows-specific file names ?

**Comment by wilcoxjay** [comment]
The issue is that on my machine, `Dafny.exe` is not actually an executable file, but must be run by passing it to the `mono` command. There is separate shell script, called `dafny` which just calls `mono Dafny.exe`. I pass `--compiler dafny` to `runTests.py`. 

But `runTests.py` tries to find the server executable by assuming that the compiler ends in `Dafny.exe` and looking for `DafnyServer.exe` in the same directory. But on my machine, the server is another shell script, called `dafny-server`.

I don't see any easy way of fixing `runTests.py` to automatically discover this script. So I think adding a flag makes sense.

**Comment by cpitclaudel** [comment]
Ah, I see. On GNU/Linux mono registers itself as a file handler and you can run the `exe` directly.  What about just detecting the platform and running dafy/dafny-server instead of Dafny.exe/DafnyServer.exe ?

**Comment by wilcoxjay** [comment]
That sounds good to me; I'll give it a shot.

**Comment by wilcoxjay** [comment]
Okay, I improved `runTests.py`'s detection of the Dafny executable on OS X. 

While I was doing this, I discovered in the Boogie documentation that the tests are already in `lit` format. The main difference I see in using `lit` vs. `runTests.py` is that the latter outputs a nice `.lst` of failing tests. Are there other differences? 

It turns out that the 4 other failing tests are due to subtle differences in the interpretation of `RUN` lines between `runTests.py` and `lit`. Under `lit`, `%t.dfy` expands differently than it does under `runTests.py`. I could try to update `runTests.py` to be in sync with `lit`, but I wanted to see whether there is any reason to continue to maintain `runTests.py`? Should I just use `lit` instead?

I also found a somewhat roundabout way of fixing `Extern.dfy`: I added a substitution to the `lit` configuration that supports substituting `%{sep}` for the pathname separator, and then used.

**Comment by cpitclaudel** [comment]
I wrote runtest.py because lit was frustratingly broken for us.  The tests ran badly on Windows, and the reporting options were bad.

**Comment by wilcoxjay** [comment]
I see, that makes sense then. I'll look more deeply into the discrepancies in interpreting `%t` substitutions when suffixes are given.

**Comment by cpitclaudel** [comment]
That being said, I was the main user of that script too (I used the comparison option to measure the performance impacts of some changes).  @RustanLeino, do you still use it, or do you use lit? If you've returned to lit, it might not make sense to maintain runTests.py

**Comment by wilcoxjay** [comment]
I am closing this because all the OS X issues mentioned are fixed. The issue of whether to maintain runTests.py is still unresolved (as far as I know, nobody uses it), but I don't think it merits leaving this issue open.
