### ISSUE TITLE
dafny insists on trigger in 1.9.7 , reports inconclusive in 1.9.9 

### ISSUE THREAD

**Issue by HPGumm** [Microsoft/dafny#102]
For the universal quantifier in predicate "surjective" Dafny issues a warning:

       "No terms found to trigger on."  

After that, verification appears to be o.k. although the quantifier  is wiggly underlined in green.

Q1: How to suppress that Warning? 

The same program does not verify in Dafny 1.9.9 The error reports start with:

Error	5	Verification inconclusive (Impl$$_module.Cantor.cantor)	
	
Error	4	Verification inconclusive (CheckWellformed$$_module.Cantor.surjective)	
etc. 

Q2: Who is right ? Dafny 1.9.7 or Dafny 1.9.9 ? 

Q3: Is there a better way than the one I chose, to specify that f is a total function? 

// ------------------ Here comes the code  -----------------------
// !!!     Note that this GitHub editor seems to display  " set " where in fact I wrote " set  &lt; G &gt; "  !!!  
  
class Cantor<G>{

predicate surjective(f : G -> set<G> )
	reads f.reads; requires forall t:: f.requires(t)    // f is a total function
ensures forall v : set<G>  :: (exists u:G :: f(u) == v) 

function cantorSet(f: G -> set<G>):set<G>
	reads f.reads; requires forall t:: f.requires(t)    // f is a total function
ensures forall x:G  :: x in cantorSet(f) <==>  x !in f(x)  

lemma cantor(f : G -> set<G>)
	requires forall t:: f.requires(t)					// f is a total function
requires surjective(f)
ensures false
{ 
  var u : G :| f(u) == cantorSet(f);
  assert false;
} 

}

**Comment by jaylorch** [comment]
Q1: To suppress the warning, you'll need to include something to trigger on. In the example I've attached, I used a simple predicate whose function is just to trigger the quantifier:

[surjectiveTrigger.dfy.txt](https://github.com/Microsoft/dafny/files/947802/surjectiveTrigger.dfy.txt)

Q2: I can't repro this, alas. When I run your example in Dafny 1.9.9 it passes. I'm using Windows, FWIW,

Q3: Yes, there is a better way. The axiomatic way you've defined surjective will let Dafny conclude that any f satisfying the reads and requires of surjective is surjective. I think you meant to put the ensures clause as the body, as I've done in the example I attached.

**Comment by HPGumm** [comment]
Jay,

thanks a lot for your help. I was not aware that my definition of 
surjective had accidentally introduced an axiom. This illustrates an 
inherent danger, when the system seems to enhance my belief in 
correctness when in fact it was my specification mistake.

As to the necessary dummy trigger for surpressing the warning, I am glad 
now, I know how this can be done, but I wish this was only an interim 
solution in Dafny in search for a more meaningful one.

Finally, I must admit, that I only half understood the semantics of what 
I myself seemed to need for successful verification: "forall g:G :: 
f.requires(g)".

I now define a predicate    isTotal(f:G -> set<G>)  to encapsulate this, 
but I must admit that I only half understood what exactly this means. 
Besides, the parameter f:G->set<G> ought to mean by itself that f is a 
total function. Where can one read enough about the semantics of Dafny 
to understand this bit?

Best regards and many thanks,

H.Peter

PS.: Here is then the current code:

class Cantor<G>{

predicate isSubset<G>(v:set<G>) { true }

predicate isTotal(f:G -> set<G>)
reads f.reads;
{
     forall g:G :: f.requires(g)
}

predicate surjective(f: G -> set<G> )
reads f.reads;
requires isTotal(f)
{
     forall v : set<G>  :: (exists g:G :: f(g) == v && isSubset(v) )
}

function {:axiom} cantorSet(f: G -> set<G>):set<G>
reads f.reads;
requires isTotal(f);
ensures forall x:G  :: x in cantorSet(f) <==>  x !in f(x)

lemma cantor(f : G -> set<G>)
requires isTotal(f) && surjective(f)
ensures 1==2     // Widerspruch
{
    var g : G :| isSubset(cantorSet(f)) && f(g) == cantorSet(f)   ;
}

}

Am 21.04.2017 um 19:24 schrieb Jay Lorch:

**Comment by jaylorch** [comment]
You don't have to worry about accidentally introducing axioms. Dafny would have warned you that you'd accidentally introduced an axiom at compilation time. If you really want a body-less function or method, you have to explicitly use {:axiom} to suppress the warning.

Triggers are indeed an annoying part of verification with quantifiers, but they're pretty fundamental to Dafny.

To read in depth about Dafny's semantics, you can read the Dafny reference manual:  https://github.com/Microsoft/dafny/blob/master/Docs/DafnyRef/out/DafnyRef.pdf

Incidentally, I tend to avoid using Dafny first-class functions (e.g., f:G->set<G>) because of all the messy need for f.reads and f.requires. I instead like to use imap's (infinite maps) to represent functions and iset's (infinite sets) to represent predicates. See the attached file for an example.

[surjectiveTrigger.dfy.txt](https://github.com/Microsoft/dafny/files/953322/surjectiveTrigger.dfy.txt)

**Comment by jaylorch** [comment]
Dafny (as of version 2.0.0) now has total, pure function types, e.g., f:int->int now refers to a function f that has no reads or requires clauses. It also has pure function types, e.g., f:int-->int refers to a function f that has no requires clauses. If you want an "old-style" heap-dependent function, use, e.g., f:int~>int.

**Comment by HPGumm** [comment]
Sounds great. I'll test them as soon as I return from vacations. Greatings from MallorcaH.Peter GummDictated to my mobile phone.-------- Originalnachricht --------Betreff: Re: [Microsoft/dafny] dafny insists on trigger in 1.9.7 , reports inconclusive in 1.9.9 (#102)Von: Jay Lorch An: Microsoft/dafny Cc: HPGumm ,Author Dafny (as of version 2.0.0) now has total, pure function types, e.g., f:int->int now refers to a function f that has no reads or requires clauses. It also has pure function types, e.g., f:int-->int refers to a function f that has no requires clauses. If you want an "old-style" heap-dependent function, use, e.g., f:int~>int.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Microsoft/dafny","title":"Microsoft/dafny","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Microsoft/dafny"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jaylorch in #102: Dafny (as of version 2.0.0) now has total, pure function types, e.g., f:int-\u003eint now refers to a function f that has no reads or requires clauses. It also has pure function types, e.g., f:int--\u003eint refers to a function f that has no requires clauses. If you want an \"old-style\" heap-dependent function, use, e.g., f:int~\u003eint.\r\n"}],"action":{"name":"View Issue","url":"https://github.com/Microsoft/dafny/issues/102#issuecomment-335568417"}}}
