### ISSUE TITLE
returning the output variable give inconclusive warning

### ISSUE THREAD

**Issue by layus** [Microsoft/dafny#105]
Example:

```dafny
method lol() returns (c: int)
{
    c := 5;
    return c;
}
```

gives `warning CS1717: Assignment made to same variable; did you mean to assign something else?`

because the code compiles `return c` to `@c = @c; return`.

```cs
  public static void @lol(out BigInteger @c)
  {
    @c = BigInteger.Zero;
  TAIL_CALL_START: ;
    @c = new BigInteger(5);
    @c = @c;
    return;
  }
```

While this is a valid translation, the warning can be confusing for newcomers. Ideally, the warning should come from Dafny itself, and such programs should compile into `return;`, without the self-assignment.

Just a bookmark for a good-first-bug-to-get-your-hands-into-Dafny issue :-)

**Comment by RustanLeino** [comment]
Good entry into filing Dafny issues, indeed. Thank you.

Oddly enough, I'm only able to get this warning if I run the C# compiler myself, but if I just run Dafny, I can't reproduce the bug.  I thought this used to be different.  Perhaps I'm using a different version of .NET where the C# compiler does not issue such warnings when invoked through the API?

In any case, I fixed the problem by include /nowarn:1717 among the compiler options passed to C#.

  Rustan
