### ISSUE TITLE
proving a forall

### ISSUE THREAD

**Issue by jiplucap** [Microsoft/dafny#107]
I expected that the following type of proof works:

forall x | P(x) {
                     calc {
                             // here a proof of Q(x)
                            } 
                      assert Q(x);
                     }
assert forall x :: P(x) ==> Q(x)

However, the last assertion is violated and the usual triggers  information is given in the hover text.

**Comment by jaylorch** [comment]
A forall statement needs an ensures clause to specify what conclusion should be visible after the forall statement. So, your code should be:

forall x | P(x)
    ensures Q(x)
{
  // here a proof of Q(x)
}
assert forall x :: P(x) ==> Q(x);

**Comment by jiplucap** [comment]
OK, thanks
