### ISSUE TITLE
inductive predicates in modules

### ISSUE THREAD

**Issue by jiplucap** [Microsoft/dafny#108]
Is it possible to use an inductive predicate defined in a module M1 inside a module M2 provided that in M2 we declare "import opened M1"?
More explicitly, I have an inductive predicate P defined in a module M1. Then, in the module M2, I need to use P#[_k], but the error "Error unresolved identifier: P#" is reported.
I have tried to write in M2 
inductive predicate {: imported} P (...)
but then another error is reported: "Error Verification process error	$$program$$	1	1"
Surprinsingly, the following
http://rise4fun.com/Dafny/MgCJ
 works in the the Dafny online. 	
But it does not work in MVS-Dafny, neither as a unique file, nor two separated files linked by an "include".

**Comment by jaylorch** [comment]
Could you provide the actual code here, or else a new link to rise4fun? The rise4fun site has been updated, and old links no longer work.

**Comment by jaylorch** [comment]
If this is still a problem, please reopen the issue.
