### ISSUE TITLE
Refinement of module facade declaration with another facade

### ISSUE THREAD

**Issue by xinhaoyuan** [Microsoft/dafny#113]
Currently it's not possible to refine a module facade declaration with another facade declaration. Please see an example in http://rise4fun.com/Dafny/3nHY.

~~I tried to fix this in my fork: https://github.com/xinhaoyuan/dafny/commit/bee08f10bfe0ab741adf4970896df2208d940c25~~

Update: the fix doesn't work on this: http://rise4fun.com/Dafny/PCQ4

**Comment by jaylorch** [comment]
The Dafny version has been updated on rise4fun.com.

**Comment by xinhaoyuan** [comment]
A minimal example would be:

```
module X { }
module Y refines X { }
abstract module A { import M : X }
abstract module B refines A { import M : Y }
```

When looking into the resolution code, I think the major problem is that resolving `ModuleFacadeDecl` would call `MakeAbstractSignature` to create an abstract `ModuleDef` without inheriting `RefinementBase`. So `CheckIsRefinement` cannot properly discover that `M : Y` refines `M : X` in module `B`.
