### ISSUE TITLE
Problem with sets and recursion

### ISSUE THREAD

**Issue by alexlesaka** [Microsoft/dafny#115]
I’m trying to work with sets of sequences of integers (i.e. {[ ],[0],[0,0],[0,1]}). There is a function that calculates the set recursively and then I want to assert if a sequence of int-s is in the set or not (i.e. assert [0.1] in S). 

When the recursion of the calculation is short (3-4 elements) there are not problems to assert if a sequence is in the set, if it is not or  that the set is equal to a fixed  set of sequence. But there is a problem when it is bigger. 

The implementation of that I’ve just explained is in the following [link](http://rise4fun.com/Dafny/cdGV). The main method prints some examples using the calculation of the set (calculatedSet) or assigning the values that are expected from the calculation manually (manualSet). 

Could somebody explain why Dafny cannot verify the last assertions saying that [0,0] and [1,0] are in calculatedSet3?

**Comment by RustanLeino** [comment]
You must be used to Dafny doing a lot of hard work for you, since you expect it to be able to also do this automatically!  Wonderful!  In fact, Dafny gets very close.  Since the functions are invoked with literals, Dafny tries to unfold the recursive invocations of the functions.  However, it gets stuck with some needed properties about sequences.  These are difficult to achieve the right amount of automation for.

If you precede your two failing assertions:

```
                        assert [0,0] in calculatedSet3; //It's not able to assert
                        assert [1,0] in calculatedSet3; //It's not able to assert
```

with the following assertion, which act as lemmas:

```
                        assert [0]+[0] == [0,0];
                        assert [1]+[0] == [1,0];
```

then all the assertions go through.  See http://rise4fun.com/Dafny/fkyf.

The most systematic way to debug something like this by yourself is to use verified calculations (the `calc` statement).  Here is such a calculation (included two nested calculations) in full detail:

```
          method Test() {
            var structure3 := B(C('x',A('T',['x'])), C('y',A('T',['y'])));
            var calculatedSet3 := setOfIndex(structure3);
            calc {
              setOfIndex(structure3);
            ==  // def. setOfIndex
              setOfIndexFrom([], structure3);
            ==  // def. setOfIndexFrom
              ({[]} + setOfIndexFrom([]+[0], C('x',A('T',['x']))) + setOfIndexFrom([]+[1], C('y',A('T',['y']))));
            ==  // simplify sequences
              ({[]} + setOfIndexFrom([0], C('x',A('T',['x']))) + setOfIndexFrom([1], C('y',A('T',['y']))));
            ==  calc {
                  setOfIndexFrom([0], C('x',A('T',['x'])));
                  // def. setOfIndexFrom
                  ({[0]} + setOfIndexFrom([0]+[0], A('T',['x'])));
                ==  { assert [0]+[0] == [0,0]; }
                  ({[0]} + setOfIndexFrom([0,0], A('T',['x'])));
                ==  // def. setOfIndexFrom
                  ({[0]} + {[0,0]});
                ==  // sets
                  ({[0], [0,0]});
                }
              ({[]} + {[0], [0,0]} + setOfIndexFrom([1], C('y',A('T',['y']))));
            ==  calc {
                  setOfIndexFrom([1], C('y',A('T',['y'])));
                ==  // def. setOfIndexFrom
                  ({[1]} + setOfIndexFrom([1]+[0], A('T',['y'])));
                ==   { assert [1]+[0] == [1,0]; }
                  ({[1]} + setOfIndexFrom([1,0], A('T',['y'])));
                ==  // def. setOfIndexFrom
                  ({[1]} + {[1,0]});
                ==  // sets
                  ({[1], [1,0]});
                }
              ({[]} + {[0], [0,0]} + {[1], [1,0]});
            ==  // sets
              ({[], [0], [0,0], [1], [1,0]});
            }
            assert [0,0] in calculatedSet3;
          }
```

  Rustan

**Comment by alexlesaka** [comment]
Thank you very for answering so fast and well! 

It is funny because I did the calculation by hand in my notebook but I didn't think about doing in dafny. 

There are some methodologies that I have to expore.

Thank you again.
