### ISSUE TITLE
VS Code plug-in not highlighting additional details on error

### ISSUE THREAD

**Issue by zehranaz** [Microsoft/dafny#119]
While working on the concurrency tutorial (the one about philosophers), when I completed the method definitions for the class, VS Code picked up on the error in the "Enter" method, but failed to highlight the extra hint in the "Valid" method above, where the conditions were actually missing. VS does have highlighting for this case.

**Comment by jaylorch** [comment]
I suggest posting this on the VS Code plugin repository instead.
