### ISSUE TITLE
Verification cache invalidation bug related to first-class functions

### ISSUE THREAD

**Issue by wilcoxjay** [Microsoft/dafny#132]
Consider the two files below. When run with `/verifySnapshots` turned on (at any level > 0), Dafny reports no errors in v1. But without `/verifySnapshots`, it reports errors in v1.

My uninformed guess is that the cache is not being invalidated when the specification of a function dependency is changed.

v0:
```
class C {
  var F : () -> ()

  function method Wrapper(): ()
    reads this, F.reads
    // this is the line that will be added in v1:
    // requires F.requires();
  {
    F()
  }

  method SetF()
    modifies this
    ensures this.F == Wrapper
  {
    this.F := Wrapper;
  }
}

method Main()
{
  var c := new C;
  c.SetF();
  var x := c.F();
}
```

v1:
```
class C {
  var F : () -> ()

  function method Wrapper(): ()
    reads this, F.reads
    // this is the line that has been added since v0:
    requires F.requires();
  {
    F()
  }

  method SetF()
    modifies this
    ensures this.F == Wrapper
  {
    this.F := Wrapper;
  }
}

method Main()
{
  var c := new C;
  c.SetF();
  var x := c.F();
}
```

**Comment by wilcoxjay** [comment]
This might in fact have nothing to do with first-class functions, and instead be a special case of #143.

**Comment by qunyanm** [comment]
Need to change the test to:
  var F : () ~> ()
to avoid the type checking error, but can't repro the cache not invalidated error.
I don't think this is related to #143 since #143 problem is specific to the code in DafnyServer.
