### ISSUE TITLE
Can prove false using inconsistent definition of map cardinality

### ISSUE THREAD

**Issue by jaylorch** [Microsoft/dafny#135]
The following lemma can be used to establish false:

lemma lemma_MapTest()
    ensures false
{
    var m := map [ 1 := 1, 2 := 1 ];
    assert m.Keys == {1, 2};
    assert m.Values == {1};
    assert |m| == |m.Keys| == 2;
    assert |m| == |m.Values| == 1;
    assert 1 == 2;
    assert false;
}

The problem is that the Dafny prelude, DafnyPrelude.bpl, has two axioms that disagree about what constitutes the size of a map.  One axiom says it's the number of keys in the map and one says it's the number of values in the map:

axiom (forall<U,V> m: Map U V :: { Set#Card(Map#Domain(m)) }
  Set#Card(Map#Domain(m)) == Map#Card(m));

...

axiom (forall<U,V> m: Map U V :: { Set#Card(Map#Values(m)) }
  Set#Card(Map#Values(m)) == Map#Card(m));

**Comment by jaylorch** [comment]
I note that the Dafny reference manual says the cardinality of a map is the cardinality of its domain, so it seems it's the second axiom that's the one that should be removed.

**Comment by RustanLeino** [comment]
Good catch. Yes, the cardinality of a map is the cardinality of its domain. The second axiom is bogus and should be removed.
