### ISSUE TITLE
Differentiate "assertion violation" into "unable to prove" and "proved false"

### ISSUE THREAD

**Issue by jerickmsft** [Microsoft/dafny#139]
It would be better if the error message was different for “unable to prove” and “was actually able to prove the opposite” without me having to try the inverse myself.
```
assert 2 == 1;
“assertion violation” becomes "assertion violation: proved false"
assert !(2 == 1);
[no error]
```

vs

```
assert forall c :: c in thread2.childrenChecked ==> this.blobs.get(c).obj >= orig[c].obj;
“assertion violation” becomes  "assertion violation: unable to prove"
assert !(forall c :: c in thread2.childrenChecked ==> this.blobs.get(c).obj >= orig[c].obj);
“assertion violation” becomes  "assertion violation: unable to prove"
```

**Comment by jaylorch** [comment]
The opposite of "assert P" isn't "assert !P". It's "Sometimes P isn't true." So even if Dafny tried the inverse itself, in most cases it wouldn't be able to prove that inverse either.
