### ISSUE TITLE
Square Root Function

### ISSUE THREAD

**Issue by slideon** [Microsoft/dafny#140]
Is there a square root function in Dafny? For reals, I saw that there is a Floor function, but I can't find sqrt. Is there a module I have to import?

**Comment by wilcoxjay** [comment]
There is no such builtin function.

You can axiomatize one for yourself. I have sketched that approach [here](https://github.com/wilcoxjay/notes/blob/874f211ff4a1e7e285290a744906ee9bf9b62f39/SquareRoot.dfy), with a small example of using square root to define the distance between points in the plane and proving that two points are equal iff their distance is 0.

If you are instead looking for integer square roots, perhaps something like what is suggested [here](http://homepage.divms.uiowa.edu/~tinelli/classes/181/Spring11/Tools/Dafny/Examples/square-root.dfy) will help you.

**Comment by slideon** [comment]
Thanks, I'll take a look at your note. I've already seen the second link, I'm looking for non-integer square roots.
