### ISSUE TITLE
Internal error related to quantifying over functions

### ISSUE THREAD

**Issue by wilcoxjay** [Microsoft/dafny#148]
Consider the following program:

```
function Foo(f: () -> (), n: nat): nat
{
    if n == 0 then n
    else Foo(f, n - 1)
}

lemma lemma_Foo()
    ensures forall g: () -> () :: Foo(g, 0) == 0  // (*)
{}

```
Dafny reports an internal assertion violation while translating the quantifier on the line marked `(*)`. 

Adding `{:induction false}` to the quantifier causes the error to go away, so the problem is probably related to computing the induction hypothesis of a quantification over a function type.

Curiously, deleting the `Foo`'s body or otherwise removing the recursive call also causes the error to go away. Perhaps the induction translation worries about recursive functions differently than other functions?

**Comment by RustanLeino** [comment]
I recently fixed this problem in the non-null_types branch.  I'll bring the change over to the main branch.

Yes, you are right about the automatic induction on quantifiers. Dafny tries to figure out which bound variables may be useful for doing induction on. If a bound variable (here, `g`) is passed as an argument to a recursive function (for a formal parameter that is part of the "decreases" clause of the callee), then it is considered to be something worth doing induction on. This heuristic is applied for quantifiers, where the heuristic for when to apply induction in lemmas is simpler and only looks at the types of the lemma's arguments.
