### ISSUE TITLE
Internal error related to type variables

### ISSUE THREAD

**Issue by wilcoxjay** [Microsoft/dafny#149]
Consider the following program:

```
function Foo<T>(m: map<int, T>): seq<T>
    ensures Foo(m) != []

lemma Bar()
    ensures forall m | 0 in m :: Foo(m)[0] == m[0]
{}
```
This program is malformed because the type of `m` is not inferable. The likely intent of the programmer was for `Bar` to take a type variable `T` which is the range type of `m`.

However, instead of reporting this problem gracefully, Dafny crashes with an internal error:
```
Assumption failed.  DEBUG: Unexpectedly confirmed XConstraint: Equatable: ? ? |||| 
```

**Comment by alexlesaka** [comment]
Hello @wilcoxjay , 

two details. As the lemma calls to a polimolphic function, one of the error is solved if you write <T> after the name (Bar<T>). 

Then, dafny is not able to infer the type of the forall, but you can write it explicitly: `forall m: map<int,T> |
`
After that, the lemma have to be completed.

```
function Foo<T>(m: map<int, T>): seq<T>
    ensures Foo(m) != []

lemma Bar<T>()
    ensures forall m:map<int,T> | 0 in m :: Foo(m)[0] == m[0]
{
	assume forall m:map<int,T> | 0 in m :: Foo(m)[0] == m[0];
}
```

Another reason could be that dafny is not able to ensure that T-type defines equality (realding the error case could be that). Try tu `<T(==)>` insted of `<T>`.

 I'm using Dafny 2.0.0. Are you too?

**Comment by wilcoxjay** [comment]
Hi @alexlesaka,

Yes, the program is definitely malformed. I also agree that there are ways of changing the program so that is not malformed.

The issue I am recording here (so that I or someone else can fix it later) is that Dafny itself crashes on this program. Dafny should never crash on any input program. Instead, it should gracefully report an error and exit if it discovers a problem with the given program.

I ran into this issue on the master branch (currently [749ec852a](https://github.com/Microsoft/dafny/tree/749ec852a6c5429796cc1aea0dfcb7de5ec53da4)). But I wouldn't be surprised if it's also present in the 2.0.0 release, since that is still very recent.

**Comment by RustanLeino** [comment]
I tried this in the non-null_types branch. There, Dafny reports a type error, but does not crash. My hope is that the non-null_types branch will be merge into the main branch once I find satisfactory heuristics for its type inference. Unless you need the fix more urgently, my suggestion for the fix of this bug is therefore to wait for the merge to take place.

  Rustan

**Comment by wilcoxjay** [comment]
That's good news!

This problem is easy to work around, so I have no problem waiting to merge for the fix.
