### ISSUE TITLE
Unreachable assertion not checked

### ISSUE THREAD

**Issue by kevinsullivan** [Microsoft/dafny#160]
Perhaps this is a feature not a bug. In any case, as an example, Dafny is happy to accept the following code without errors, despite the invalid assertion after the returns.

method Abs(x: int) returns (y: int)
        ensures y >= 0
    {
        if (x < 0) { return -x; } else { return x; }
        assert 5 < 5;
    }
}

**Comment by jaylorch** [comment]
Yes, that's a feature. The fact that the code is unreachable is what makes the assertion of a false statement OK.

**Comment by kevinsullivan** [comment]
Ok, thanks.
