### ISSUE TITLE
VSCode/Dafny problem -- Presumably a Dafny server error, but cryptic non-end-user error code

### ISSUE THREAD

**Issue by kevinsullivan** [Microsoft/dafny#165]
I'm writing some very basic code in Dafny for a class I'm teaching. Single file. Nothing unusual. I'm getting this error occasionally. "Message: Request textDocument/definition failed with message: Cannot read property 'then' of null Code: -32603". I don't know what this means and don't have time at the moment to try to debug it. Maybe a dev will know what's up. Thanks all. --Kevin

**Comment by kevinsullivan** [comment]
A note: I see a similar issue on the VSCode repo. https://github.com/Microsoft/vscode/issues/15185. If this report belongs over there, just resolve it here and let me know and I will start to watch that issue there. --Kevin

**Comment by fabianhauser** [comment]
This is a Dafny-VSCode problem. We have an open issue over there: DafnyVSCode/Dafny-VSCode#12.
