### ISSUE TITLE
Spilling .cs code without compiling it

### ISSUE THREAD

**Issue by palmskog** [Microsoft/dafny#187]
Maybe I'm missing something, but I can't find an option to make Dafny produce `.cs` code without trying to compile it. This is a problem when calling Dafny-external methods from Dafny code, as in the [extern test](https://github.com/Microsoft/dafny/blob/master/Test/dafny0/Extern.dfy). The `.cs` file produced from such Dafny code won't be compilable without another `.cs` file defining the external methods, and so Dafny will return an error.

The only workaround I've been able to think of is to have the build system ignore the compilation error (since the `.cs` code is still spilled), e.g., using a dash in `make`:
```
Extern.exe: Extern.cs Extern2.cs ExternHelloLibrary.dll
	mcs /r\:System.Numerics.dll /r\:ExternHelloLibrary.dll Extern.cs Extern2.cs

Extern.cs: Extern.dfy
	-Dafny.exe /compile\:1 /spillTargetCode\:1 /nologo Extern.dfy
```

If there is indeed currently no way to make Dafny avoid the final compilation step, would a pull request to introduce this be welcome?

**Comment by RustanLeino** [comment]
Good point. Apparently, this has not come up before. I will provide some new `/spillTargetCode` options that fix this.

Note, if you don't need further processing, it is also possible to add your additional `.cs` and `.dll` files to the Dafny command line. Dafny will then pass them on to the C# compiler.

Mvh,
  Rustan

**Comment by palmskog** [comment]
Thanks, great!

The problem we have with passing `.dll` files on the Dafny command line is that Dafny then seemingly requires `DafnyRuntime.dll` to be in a known assembly location. I believe this is because of the following [line](https://github.com/Microsoft/dafny/blob/d529947abecb5c5bf9c8944f309593ce818ec2b3/Source/Dafny/DafnyMain.cs#L44) in `DafnyMain.cs`:
```
Assembly.ReflectionOnlyLoad("DafnyRuntime");
```
Without the `.dll`, I get a `FileNotFoundException`. In, for example, the Ubuntu distribution of Dafny, `DafnyRuntime.dll` is not bundled as a binary, and so must be manually compiled. This would be a headache when packaging and building our project, since we prefer embedding the Dafny runtime library directly in the final project `.dll`.
