### ISSUE TITLE
Trivial assertion involving sequence concatenation fails

### ISSUE THREAD

**Issue by sprt** [Microsoft/dafny#190]
This assertion fails under the last version of Dafny:

    assert [] + [false] != [] + [true];

Is there a way to work around it at least?

**Comment by wilcoxjay** [comment]
Here is a (somewhat hacky) workaround:

    assert [] + [false] == [false];
    assert [] + [true] == [true];
    assert [false] != [true];
    assert [] + [false] != [] + [true];

In general, equality between collections is hard for Dafny, due in part to encoding of extensionality. Things get especially bad on medium-small concrete examples, which is unintuitive.

My strategy to find a workaround like this is to start asserting simpler things that might be part of a human-level argument to convince someone of the assertion. 

(A puzzle for some readers: commenting out either of my first two assertions still works; commenting out both fails; why?)

**Comment by sprt** [comment]
Interesting. Is there a way to make the following assertion pass? I couldn't find one.

    assert input + [false] != input + [true];

where `input` is of course of type `seq<bool>`.

**Comment by wilcoxjay** [comment]
Here is one way

    if input + [false] == input + [true] {
        var l := input + [false];
        assert l[|l|-1] == false;
        assert l[|l|-1] == true;
        assert false;
    }
    assert input + [false] != input + [true];
