### ISSUE TITLE
Wrong C# Equals code for parameterized datatypes with sequences without equality annotation

### ISSUE THREAD

**Issue by palmskog** [Microsoft/dafny#195]
Consider the following (_completely_ [random](https://github.com/certichain/toychain)) program that Dafny successfully verifies:
```
datatype Block<Hash,Transaction,VProof> = 
  Block(prevBlockHash:Hash, txs:seq<Transaction>, proof:VProof)

function method GenesisBlock() : Block<int,int,int> {
  Block(0, [], 0)
}

method IsGenesisBlock(b : Block<int,int,int>) returns (eq : bool)
  ensures eq <==> b == GenesisBlock();
{
  var gb := GenesisBlock();
  eq := b == gb;
}

method Main() {
  var b := GenesisBlock();
  var eq := IsGenesisBlock(b);
  assert eq;
  print eq, "\n";
}
```
I expected this program, when compiled to .NET assembly, to print `True` (because `assert eq` passes without complaint), but in fact it prints `False`. 

The problem is that Dafny generates the following `Equals` method for the C# class for `Block`:
```
public override bool Equals(object other) {
  var oth = other as Block_Block<@Hash,@Transaction,@VProof>;
  return oth != null &&
    Dafny.Helpers.AreEqual(this.@prevBlockHash, oth.@prevBlockHash) &&
    this.@txs == oth.@txs &&
    Dafny.Helpers.AreEqual(this.@proof, oth.@proof);
}
```
That is, the comparison for the field `txs` isn't deferred to `Dafny.Helpers.AreEqual`, and the runtime representations of the sequences (of class `Dafny.Sequence`) are different objects, so the conjunction always returns `False` in practice.

Why does this happen? Well, because `SeqType` defers whether it supports equality to its parameter type in `DafnyAst.cs`:
```
public override bool SupportsEquality {
  get {
    // The sequence type supports equality if its element type does
    return Arg.SupportsEquality;
  }
}
```
And in our case, the type parameter `Transaction` is not known to support equality (does not have the `==` annotation). This suggests that a workaround is to define `Block` as follows:
```
datatype Block<Hash,Transaction(==),VProof> = 
  Block(prevBlockHash:Hash, txs:seq<Transaction>, proof:VProof)
```
And indeed this makes the compiled program print the correct value (`True`). However, in the general case, this restricts the concrete types that `Block` can be parameterized with. 

I'm not sure what the best solution to this problem is (or indeed if the problem is already known), but it seems unsatisfactory to have this disconnect between the verified Dafny program and its C# representation.

**Comment by RustanLeino** [comment]
Thanks for the bug report. There should be no disconnect between the verified Dafny program and its C# representation.
