### ISSUE TITLE
Dafny 1.9.3

### ISSUE THREAD

**Issue by jiplucap** [Microsoft/dafny#197]
I need to install Dafny 1.9.3. Please, could you tell me how to download it?
Paqui

**Comment by wilcoxjay** [comment]
There is no binary release of Dafny 1.9.3 on github. The best you can do is check out a revision from the git history that has version 1.9.3. For example, you could try [this one](https://github.com/Microsoft/dafny/tree/4235fe78892959d98e9ceb79c4cdf509f4aa513c). You can browse other old version revisions [here](https://github.com/Microsoft/dafny/commits/master/Source/version.cs).

**Comment by jiplucap** [comment]
Thanks, Paqui
