### ISSUE TITLE
README should also point to the community

### ISSUE THREAD

**Issue by jorendorff** [Microsoft/dafny#198]
I have a user-level question, but I can't tell where to ask it. There must be a mailing list, chat app, forum, or something where Dafny people talk. Right?

There's always StackOverflow...

**Comment by wilcoxjay** [comment]
There is currently no such discussion list.

We should have one! I'll look into it.

**Comment by wilcoxjay** [comment]
Fixed by [cea3bc](https://github.com/Microsoft/dafny/commit/cea3bcd91c1c46dba6294cf9999827ba10d2f46e).
