### ISSUE TITLE
Cannot prove that a boolean field has a 'false' value in a constructor

### ISSUE THREAD

**Issue by manuelmontenegro** [Microsoft/dafny#204]
Given this simple class:

```dafny
class A {
	var x: bool;

	constructor()
	  ensures x == false
	{
		x := false;
	}
}
```

Dafny reports that the postcondition of the constructor might not hold. 

```
Error BP5003: A postcondition might not hold on this return path.
```

Apparently it only happens when the value assigned and checked in the postcondition is `false`. If we replace it by `true`

```dafny
	constructor()
	  ensures x == true
	{
		x := true;
	}
```

Then Dafny does not complain. In fact, I have tried with other values (numbers, null references, etc.) and `false` seems to be the only one for which Dafny cannot prove the postcondition.

If I replace the constructor by an initialization method, it goes fine:

```dafny
	method Init()
		modifies this
		ensures x == false
	{
		x := false;
	}
```

I'm using Dafny 2.1.1.10209

**Comment by jamesbornholt** [comment]
This looks like the same issue as #194. Does [the workaround](https://github.com/Microsoft/dafny/issues/194#issuecomment-385230373) there fix things?

**Comment by manuelmontenegro** [comment]
Yes, it works for me. Thank you and sorry for the dupe.
