### ISSUE TITLE
Can't show that old(x).func() == old(x.func())

### ISSUE THREAD

**Issue by jerickmsft** [Microsoft/dafny#207]
I was working on some weird errors and I think I narrowed down the problem to this:

```
datatype Maybe<T> = Some(T) | None

class Test
{
  var m : map<int,int>;
  
  function method tryGet(k: int) : (v : Maybe<int>)
    reads this
    {
      if (k in m) then Some(m[k]) else None
    }
    
   method tryInsert(k: int, v: int) returns (r: bool)
    modifies this
    ensures forall i :: i in m ==> old(this).tryGet(i) == old(this.tryGet(i))
    {
      if (k in m) { r := false; } else {m := m[k := v]; r := true;}
    }
}
```

What I'm seeing is that Dafny doesn't see the equivalence of `old(x).func()` and `old(x.func())`.  Maybe I mistaken, but I think these are the same.

**Comment by RustanLeino** [comment]
`old(E)` means that the values that `E` looks up _in the heap_ are instead looked up in the heap on entry to the method. Stated differently: roughly speaking, you should think of `old` as altering every occurrence of `.` (field dereference) and `[ ]` (array dereference) in the expression argument you give it. In particular, if `x` is a parameter or local variable or bound variable, then `old(x)` means the very same thing as `x`.

Yet again, `this` is a pointer and that pointer is the same whether or not you wrap `old` around it. However, if you _dereference_ that pointer, then it makes a difference whether or not you wrap `old` around the dereferencing expression. Suppose `g` is a field of the enclosing class. Then, `this.g` (or just `g`) refers to the current value of the `g` field of the pointer `this`, and `old(this.g)` (or just `old(g)`) refers to the initial value (that is, the value on entry to the enclosing method) of the `g` field of that same pointer `this`. Likewise, `this.func()` refers to the value you get if you call function `func()` on `this` in the current state, while `old(this.func())` refers to the value you would have got from calling `func()` on `this` in the initial state.

  Rustan

**Comment by jerickmsft** [comment]
Thanks!  Your description makes it much clearer in my mind.

I'll put out a PR to reference manual to see if I can make it more explicit.  Currently, it states:

> old(e) evaluates to the value expression e had on entry to the current method. Note that old only affects heap dereferences"

While I now understand this to be true and accurate, I had found a bit confusing as I had confused `this` _logically_ being a heap object (and thus any access upon it being a heap dereference) and `this` _physically_ being a local variable that is a pointer to a heap object.

If I end up feeling particularly adventurous, I'll see if I can make a new compiler warning :)

> old(...) contains an expression without any heap dereferences and thus has no effect

John

Here's some of my debugging that might help the next person who ends up here:
```
datatype Maybe<T> = Some(T) | None

class Test
{
  var m : map<int,int>;
  
  function method tryGet(k: int) : (v : Maybe<int>)
    reads this
    ensures v == if (k in m) then Some(m[k]) else None
    {
      if (k in m) then Some(m[k]) else None
    }
    
   method tryInsert(k: int, v: int) returns (r: bool)
    modifies this
    ensures forall i :: i in old(m) ==> old(this).tryGet(i) == old(this.tryGet(i))
    ensures forall i :: i in old(m) && i != k ==> old(this).tryGet(i) == this.tryGet(i)
    ensures !r ==> old(this).tryGet(k) == this.tryGet(k)
    ensures !r ==> old(this).tryGet(k) == old(this.tryGet(k))
    ensures r ==> old(this).tryGet(k) == this.tryGet(k)
    ensures forall i :: i in m && i != k ==> old(this).tryGet(i) == old(this.tryGet(i))
    ensures r ==> old(this.tryGet(k)) == None
    ensures r ==> !old(k in this.m)
    ensures r ==> !(k in old(this.m))
    ensures !r ==> old(this.m) == old(this).m
    ensures r ==> old(this.m.Keys - {k}) == old(this).m.Keys - {k}
    ensures r ==> {k} * old(this.m.Keys) == {}
    ensures r ==> {k} * old(this.m).Keys == {}
    ensures r ==> {k} * old(this).m.Keys == {}
    {
        if (k in m) { 
            r := false;
        } else {
            m := m[k := v];
            r := true;
        }
    }
}
```
