### ISSUE TITLE
Next Dafny release?

### ISSUE THREAD

**Issue by palmskog** [Microsoft/dafny#208]
There have been many improvements and bug fixes since the last Dafny [release](https://github.com/Microsoft/dafny/releases/tag/v2.1.1). We have projects that could be simplified quite a lot using a Dafny version with these changes. At the same time, we prefer relying on an official release with binaries for all platforms.

Is there any chance for a new official release of Dafny on GitHub in the near future?

**Comment by wilcoxjay** [comment]
@palmskog just wanted to give you an update. The Dafny team is discussing this out of band and we hope to cut a release sometime soon. Thanks for your patience!

**Comment by wilcoxjay** [comment]
Dafny 2.2.0 was released several weeks ago, so I'm going to mark this resolved!
