### ISSUE TITLE
Dafny build from source on Linux missing msbuild

### ISSUE THREAD

**Issue by OrenGitHub** [Microsoft/dafny#212]
Hi,
I'm trying to build Dafny from source according to the `INSTALL.md` file.
All goes well until I'm asked to build Boogie with this line:

    msbuild Source/Boogie.sln

Because `msbuild` is missing.
What should I do? Thanks!

**Comment by wilcoxjay** [comment]
`msbuild` should come with `mono`. What is the output of running the following command?

    mono --version

**Comment by OrenGitHub** [comment]
Here it is:

    Mono JIT compiler version 4.6.2 (Debian 4.6.2.7+dfsg-1ubuntu1)
    Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
    	TLS:           __thread
    	SIGSEGV:       altstack
    	Notifications: epoll
    	Architecture:  amd64
    	Disabled:      none
    	Misc:          softdebug 
    	LLVM:          supported, not enabled.
    	GC:            sgen

**Comment by wilcoxjay** [comment]
I believe `msbuild` was introduced in version 5. One option is to upgrade your installation of mono.

If you don't want to do that, you can also try using `xbuild` instead of `msbuild`, although I'm not sure whether Dafny still works with mono version 4.

**Comment by OrenGitHub** [comment]
Yes upgrading to mono 5 solved it. Thanks!
