### ISSUE TITLE
Dafny crashes when quantifier appears in implicit trigger

### ISSUE THREAD

**Issue by jaylorch** [Microsoft/dafny#215]
The following code causes Dafny to crash with the error "quantifiers are not allowed in triggers":

    module Test {
      datatype A = A1
      datatype B = B1
    
      function Convert_AB(f:A) : B { B1 }
      function Convert_BA(f:B) : A { A1 }
    
      function ConvertMap_AB(m:map<A, int>) : map<B, int>
      {
        var dom_B := set a | a in m :: Convert_AB(a);
        map b | b in dom_B :: m[Convert_BA(b)]
      }
    }

**Comment by jamesbornholt** [comment]
I think this is #167 again.
