### ISSUE TITLE
rprint doesn't preserve important parentheses

### ISSUE THREAD

**Issue by jaylorch** [Microsoft/dafny#228]
When I include parentheses in a Dafny file to override the normal order of operations, then /rprint the file, /rprint doesn't print the relevant parentheses.  For instance, if I run `Dafny.exe test.dfy /rprint test-alt.dfy` on this file:

```
module Test1 {
    lemma lemma_Test(s:seq<int>, t:seq<int>, u:seq<int>)
        ensures  (s + t) + u == (s + t) + u
    {
    }
}
```

it prints the post-condition as:

```
ensures s + t + u == s + t + u
```

**Comment by wilcoxjay** [comment]
Marking as closed. (The commit message ace7afb3 incorrectly refers to non-existant issue #288.)

**Comment by RustanLeino** [comment]
Boy, it seems I managed several silly errors in my previous commit (and commit comment). Thanks for pointing those out. I hope I have fixed the machine-specific one now.
