### ISSUE TITLE
Type system link broken.

### ISSUE THREAD

**Issue by Hoblovski** [Microsoft/dafny#230]
On master branch on March 19th, 2019, the *Language reference for the Dafny type system, which also describes available expressions for each type* link on README.md is broken.

[Link](https://github.com/Microsoft/dafny/blob/c697132a86a90f889ff89ec2e805a79a25e24128/README.md#read-more) to the README.md is here.

The [target](http://research.microsoft.com/en-us/um/people/leino/papers/krml243.html) redirects to [Microsoft people](https://www.microsoft.com/en-us/research/people/).

**Comment by RustanLeino** [comment]
I updated this link. The document itself is a bit out of date, but it's probably still a useful reference.
