### ISSUE TITLE
Unable to export functions with a reads clause

### ISSUE THREAD

**Issue by arkadiyf** [microsoft/dafny#238]
The following code raises an error in Dafny:
```
module A {
    // Either of the following lines raises an error:
    // export reveals B, B.C
    export reveals *
    class B {
        predicate C() 
            reads this
        {
            true
        }
    }
}
```
The error I see is:
```
The signature of function C depends on type B which was not exported with it. Ensure that B is visible wherever C is exported.
```
This error goes away when I remove the `reads this`, but otherwise I haven't found a way to make it work.

**Comment by RustanLeino** [comment]
Thanks for the bug report. This was recently fixed in commit https://github.com/microsoft/dafny/commit/9fd0ef7edaaa58f872c0b8527e194b9081a06dd0. You can pick this fix up immediately if you're building Dafny from source.
