### ISSUE TITLE
Arrays, subset types, and generics

### ISSUE THREAD

**Issue by parno** [Microsoft/dafny#29]
In the example below, I get "Error: value does not satisfy the subset constraints of 'array<int>'" when I try to pass an array of uint32s (a subset type) to a function (`ArrayIdentity`) that is generic over array types.  Oddly, it works when I do the same test with sequences or if the entire array is treated as the generic type (e.g., when calling `Identity`).

```
function Identity<T>(a:T) : T
{
  a
}

function SeqIdentity<T>(s:seq<T>) : seq<T>
{
    s
}

function ArrayIdentity<T>(a:array<T>) : array<T>
{
    a
}

type uint32 = i : int | 0 <= i < 0x1_0000_0000

lemma test()
{
    var x:uint32;
    var g := Identity(x);     // Works
    
    var s:seq<uint32>;
    var s' := Identity(s);      // Works
    var s'' := SeqIdentity(s);  // Works

    var a:array<uint32>;
    var a' := Identity(a);    // Works
    var a'' := ArrayIdentity(a);  // Error    
}
```

**Comment by parno** [comment]
It appears sequences are also affected by this bug (or possibly a related one).  Here's an example where generics cause Dafny to lose track of subset type constraints:

```
type uint32 = i:int | 0 <= i < 0x1_0000_0000

function ConcatenateSeqs<T>(ss:seq<seq<T>>) : seq<T>
predicate WordSeqToBytes(ws:seq<uint32>) 

method test(M:seq<seq<uint32>>)
{
    ghost var t := WordSeqToBytes(ConcatenateSeqs(M));
}
```
Dafny reports: "Error: value does not satisfy the subset constraints of 'seq<uint32>'"

**Comment by 0xabu** [comment]
Sounds like this is related to (or the same bug as) #27?
