### ISSUE TITLE
F5 in VS extension discards cached results

### ISSUE THREAD

**Issue by jaylorch** [Microsoft/dafny#30]
I use the Visual Studio extension a lot, and I was excited to have the ability to start and stop verification using F5.  However, it's not as useful as I'd hoped it would be, because every time I use it it seems to throw away the cache of verification results!  I'd find it useful if this weren't the case.

The common scenario I find myself in is:
1) I make some changes to a lemma, and the plugin starts verifying them.
2) While it's in the middle of verification, I realize I have a bug in the changes I just made and I make some more changes to fix that bug.
3) I hit F5 to say, "Stop verifying now, because I know you're going to fail."
4) I hit F5 to say, "Start verifying again, because I've made changes that will help you succeed."

But, all the savings I was hoping to get by stopping its futile attempt at verification are moot, because it threw away cache results for the entire file.  So instead of saving a few seconds of futile verification time, I actually lose minutes of time by having to re-verify the entire file.

**Comment by 0xabu** [comment]
Wouldn't it make more sense to restart verification immediately as soon as there are new changes, and not require any explicit action to cancel the verification? I've often wished the Emacs mode worked this way.

**Comment by jaylorch** [comment]
Sure, restarting verification immediately as soon as there are new changes sounds even better, as long as we don't throw away cached verification results when we do so.

**Comment by RustanLeino** [comment]
I thought the Emacs mode for Dafny already does kill any ongoing verification when the buffer has been modified (whereas the Visual Studio mode does not).

**Comment by cpitclaudel** [comment]
Nope; Emacs waits for a full verification round to complete before starting another one.

The reason is mostly technical, I think: back when I wrote this code, I don't think Dafny had a nice API to interrupt an ongoing verification without loosing the partial results.

I'm not sure restarting after every modification is the best.  That's going to be a lot of restarts.

What about restarting every time the file is saved?

Clément.

**Comment by 0xabu** [comment]
Restarting on save sounds like a good option to me.

**Comment by jaylorch** [comment]
Fine with me as well.
