### ISSUE TITLE
Dafny can't see fact about subset type in calc

### ISSUE THREAD

**Issue by jaylorch** [Microsoft/dafny#41]
In the following code, Dafny fails to see the calc equality relationship holds, even though it follows directly from the statement of the lemma:

type uint32 = i:int | 0 <= i < 0x1_0000_0000

function last<T>(s:seq<T>):T
    requires |s| > 0;
{
    s[|s|-1]
}

function all_but_last<T>(s:seq<T>):seq<T>
    requires |s| > 0;
    ensures  |all_but_last(s)| == |s| - 1;
{
    s[..|s|-1]
}

function ConcatenateSeqs<T>(ss:seq<seq<T>>) : seq<T>
{
    if |ss| == 0 then [] else ss[0] + ConcatenateSeqs(ss[1..])
}

lemma {:axiom} lemma_ReverseConcatenateSeqs<T>(ss:seq<seq<T>>)
    requires |ss| > 0;
    ensures  ConcatenateSeqs(ss) == ConcatenateSeqs(all_but_last(ss)) + last(ss);

lemma Test(word_seqs:seq<seq<uint32>>, words:seq<uint32>)
{
    var word_seqs' := word_seqs + [words];

    calc {
        ConcatenateSeqs(word_seqs');
            { lemma_ReverseConcatenateSeqs(word_seqs'); }
        ConcatenateSeqs(all_but_last(word_seqs')) + last(word_seqs');
    }
}

**Comment by parno** [comment]
Is this the same problem as Issue #40?

**Comment by qunyanm** [comment]
Can you update the test? It failed to resolve even after I added type argument <T> to the functions and changed argument type from seq to seq<T>.

**Comment by jaylorch** [comment]
Hmm, maybe something went wrong with copy-paste.  Here's the Dafny file, renamed to .txt so that github will accept it.

[test.dfy.txt](https://github.com/Microsoft/dafny/files/516726/test.dfy.txt)

**Comment by jaylorch** [comment]
Here's an even simpler version of the test, attached.  It shows that the problem is with the calc; an alternate version that invokes the lemma at top level lets Dafny see that the equality holds.

[test2.dfy.txt](https://github.com/Microsoft/dafny/files/516745/test2.dfy.txt)

**Comment by jaylorch** [comment]
Here's another, even simpler, test that suggests the problem might not just be about calc.  It seems to be related to the use of a subset type as a generic type.

[test3.dfy.txt](https://github.com/Microsoft/dafny/files/516768/test3.dfy.txt)

**Comment by jaylorch** [comment]
To reply to parno's comment:  yes, this is hopefully due to the same underlying problem as issue #40.
