### ISSUE TITLE
<==> operator does not appear to chain as expected

### ISSUE THREAD

**Issue by 0xabu** [Microsoft/dafny#52]
Given the following definitions:
```
datatype mode = User | FIQ | IRQ | Supervisor | Abort | Undefined | Monitor

predicate bad(a:map<mode, int>, b:map<mode, int>)
{
    (forall m:mode :: m != User <==> m in a <==> m in b)
    && (forall m:mode :: m != User ==> a[m] == b[m])
}

predicate good(a:map<mode, int>, b:map<mode, int>)
{
    (forall m:mode :: (m != User <==> m in a) && (m != User <==> m in b))
    && (forall m:mode :: m != User ==> a[m] == b[m])
}
```
I would expect `good` and `bad` to be equivalent (I've just expanded the chained `<==>` operator), however Dafny reports an "element may not be in domain" error on `b[m]` in `bad`. Either I'm hopelessly confused, or the operator is not chaining the way I would expect.

**Comment by RustanLeino** [comment]
`<==>` is not a chaining operator in Dafny. It is associative. See section 0.0 of http://research.microsoft.com/en-us/um/people/leino/papers/krml243.html.

If you'd like, you can use `==`, which is chaining:

```
forall m:mode :: (m != User) == (m in a) == (m in b)
```

  Rustan

**Comment by 0xabu** [comment]
Oops! In my defense, @Chris-Hawblitzel was under the same delusion...
