### ISSUE TITLE
Some files still have Ms-PL licence headers

### ISSUE THREAD

**Issue by bbarenblat** [Microsoft/dafny#54]
Despite the project being relicensed under the Expat licence, some files still have Ms-PL licence boilerplate at the top. A quick grep finds

- Source/DafnyExtension/
  + BufferIdleEventUtil.cs
  + ErrorTagger.cs
  + IdentifierTagger.cs
  + OutliningTagger.cs
  + ResolverTagger.cs

After confirming that leaving those headers intact was not deliberate, please change them to refer to the Expat licence or remove them entirely.

**Comment by cpitclaudel** [comment]
Sorry, I missed these when I moved the project to GitHub.  @RustanLeino, can you push the required change?

**Comment by cpitclaudel** [comment]
Thanks!
