### ISSUE TITLE
feature request: declaring constants

### ISSUE THREAD

**Issue by Chris-Hawblitzel** [Microsoft/dafny#6]
Boogie supports both const declarations and function declarations:

```
const c:int; axiom c == 3;
function f(i:int):int { i + 1 }
```

Dafny doesn't have const declarations, which means you have to write c as a zero-argument function:

```
function c():int { 3 }
function f(i:int):int { i + 1 }
```

It would be nice to be able to write something like:

```
const c:int { 3 }
const c:int := 3
const c:int = 3
```

and then refer to c in the rest of the program as "c", not "c()".

**Comment by parno** [comment]
FWIW, I'd vote for the second syntax: 
```
const c:int := 3
```

**Comment by parno** [comment]
In discussing this with Chris, we posited two possible ways to implement this on the Boogie side.  The simplest would be to make use of Boogie constants.  The only question is whether the way Boogie defines constants (via an axiom) might inhibit Z3 in certain cases.  Boogie supports inlining functions, so if it supports inlining constants, then we're set.  If it doesn't, then we might be better off defining a Boogie-level function for each constant, and then marking the function as inline.

**Comment by qunyanm** [comment]
Each constant is emitted as a Boogie-level function marked with {:inline} attribute since I didn't find any code in Boogie that supports inlining constants.
