### ISSUE TITLE
datatype update error

### ISSUE THREAD

**Issue by jonnadal** [Microsoft/dafny#60]
Datatype updates as outlined in https://research.microsoft.com/en-us/um/people/leino/papers/krml243.html are rejected on my machine with a message indicating "update requires a sequence, map, multiset, or datatype".

- Environment: OS X 10.10.5, Darwin Kernel Version 14.5.0
- Dafny Version: 1.9.8.30829

Repro:

```
$ /usr/local/bin/mono /opt/dafny/Dafny.exe /version
Dafny program verifier version 1.9.8.30829, Copyright (c) 2003-2016, Microsoft.
*** Error: '/version': Filename extension '' is not supported. Input files must be Dafny programs (.dfy) or C# files (.cs) or managed DLLS (.dll)

$ cat datatype-update.dfy
datatype MyType = MyType(f1: int, f2: int)
method Repro()
{
    var x := MyType(0, 0);
    var y := x[f1 := 1];
}

$ /usr/local/bin/mono /opt/dafny/Dafny.exe datatype-update.dfy
Dafny program verifier version 1.9.8.30829, Copyright (c) 2003-2016, Microsoft.
datatype-update.dfy(5,15): Error: unresolved identifier: f1
datatype-update.dfy(5,14): Error: update requires a sequence, map, multiset, or datatype (got MyType)
2 resolution/type errors detected in datatype-update.dfy
```

Expected behavior would be for the above to typecheck, with `y == MyType(1, 0)` as suggested by the following quote from the docs referenced above:

> As an alternative to calling a datatype constructor explicitly, a datatype value can be constructed as a change in one parameter from a given datatype value using the datatype update expression. For any d whose type is a datatype that includes a constructor C that has a parameter (destructor) named f of type T, and any expression t of type T,
> 
> d[f := t]
> 
> constructs a value like d but whose f parameter is t. The operation requires that d satisfies C?. For example, the following equality holds:
> 
> Cons(4, Nil)[tail := Cons(3, Nil)] == Cons(4, Cons(3, Nil))

**Comment by parno** [comment]
The error message is rather confusing, but the underlying problem is that the syntax for datatype updates has changed.  Try doing: `x.(f1 := 1)` instead.

**Comment by jonnadal** [comment]
That worked. Thanks!

```
$ cat datatype-update.dfy
datatype MyType = MyType(f1: int, f2: int)
method Repro()
{
    var x := MyType(0, 0);
    var y := x.(f1 := 1);
}

$ /usr/local/bin/mono /opt/dafny/Dafny.exe datatype-update.dfy
Dafny program verifier version 1.9.8.30829, Copyright (c) 2003-2016, Microsoft.

Dafny program verifier finished with 2 verified, 0 errors
Compiled assembly into datatype-update.dll
```
