### ISSUE TITLE
Version 1.9.3.20406

### ISSUE THREAD

**Issue by jiplucap** [Microsoft/dafny#61]
Hi,
I need to install Dafny version 1.9.3.20406 for MVS. I look for it, but only the two last releases are available, or maybe I could find any previous release. Please, could you send me that version or give me instructions to reach it in the web.

Paqui Lucio 
e-mail: paqui.lucio@ehu.es

**Comment by cpitclaudel** [comment]
http://dafny.codeplex.com/releases/view/620771

**Comment by jiplucap** [comment]
Thank you, Paqui
