### ISSUE TITLE
Induction Hypothesis

### ISSUE THREAD

**Issue by jiplucap** [Microsoft/dafny#65]
Why the induction hypothesis is not verified in this trivial lemma?
http://rise4fun.com/Dafny/lvtUA

**Comment by RustanLeino** [comment]
Getting non-linear arithmetic through the verifier is often tricky.  The problem in this case, I'm guessing, is that the SMT solver rewrites the formula in the assertion but does not rewrite the postcondition of the recursive call, after which it is it no longer obvious that the asserted condition would hold.

Here are two workarounds that sometimes help.  One possible workaround is to use a local variable to introduce a name for the expression `n-1` in the assertion.  This name may keep the SMT solver from forgetting the given shape of the formula.  (Note that Dafny performs substitutions for let expressions, so a let expression is not as likely to work as with local variable.)  Another possible workaround is to give a name to a formula by introducing a function.  Such a function can then help "contain" the non-linear part of the formula.

Your example also requires an additional assertion lemma about non-linear arithmetic, which the SMT solver can prove.  So, here are two versions of your program that verify:

http://rise4fun.com/Dafny/gza9

http://rise4fun.com/Dafny/AHDD7

  Rustan

**Comment by jiplucap** [comment]
I see. A million of  thanks, Paqui
