### ISSUE TITLE
Domain/Range/Pairs members for maps

### ISSUE THREAD

**Issue by RustanLeino** [Microsoft/dafny#70]
Feature request:  `.Domain`, `.Range`, and `.Pairs` for `map` and `imap` types.

The types `map` and `imap` ought to have three built-in members, `.Domain`, `.Range`, and `.Pairs`.
For `map<A,B>`, the types of these members are:

```
.Domain : set<A>
.Range : set<B>
.Pairs : set<(A,B)>
```

and for `imap<A,B>`, the types are:

```
.Domain : iset<A>
.Range : iset<B>
.Pairs : iset<(A,B)>
```

(Is there a better name for `.Pairs`?)

  Rustan

**Comment by jaylorch** [comment]
Python calls the set of <key, value> pairs in a dictionary "items", as in items() and iteritems(). So another possible name for the iset<(A,B)> is Items.

**Comment by RustanLeino** [comment]
Good idea.  Reflecting on it, I also think `Key`/`Value` is better than `Domain`/`Range`, because `Domain`/`Range` could possibly be confused with the types `A`/`B` (which are in general supersets of the keys/values contained in the map).

I just found this marvelous page:  http://rosettacode.org/wiki/Associative_array/Iteration.  It shows how more than 100 languages deal with this issue.  The top of the page uses the words "key-value pairs".

.NET also uses the names `Keys`/`Values`.  To get the items (pairs) of a `Dictionary` `d`, one simply mentions `d` as the enumerator (rather than `d.Keys` or `d.Values`).  I'd like to move in this direction for Dafny as well, to make `x in m` mean `x in m.Items`, whereas today in Dafny `x in m` means `x in m.Keys`.

Apparently, Java (somewhat inconsistently) uses the names `keySet`/`elements`.  I like "values" better than "elements" (probably because I'm more used to .NET).  Different versions of Java also offer the items either as `entrySet` or using the method `forEach`.

So, I suggest we use `Keys`, `Values`, and `Items`.

  Rustan
