### ISSUE TITLE
Comparing Sequences

### ISSUE THREAD

**Issue by jiplucap** [Microsoft/dafny#76]
I think that there is some bug in comparing sequences (in particular, strings). 

http://rise4fun.com/Dafny/BtDm

Is there?

Some days ago I wrote in the "Discussions" site about the same problem on strings.
Thanks,
Paqui

**Comment by RustanLeino** [comment]
For your program:

```
assert [0,0] in {[0,2],[1,2]} ;
```

Dafny reports an error, saying the assertion does not hold.  That seems the desired outcome.  Are you seeing something different?

  Rustan

**Comment by RustanLeino** [comment]
Oh, but the two examples from your Discussion post (http://rise4fun.com/Dafny/SNDyT, http://rise4fun.com/Dafny/19Sh) do show a problem.

  Rustan

**Comment by jiplucap** [comment]
Hi Rustan,
I'm sorry, I would report this:

http://rise4fun.com/Dafny/zvXO

Thanks,
Paqui

**Comment by RustanLeino** [comment]
Thanks, Paqui.  This test case works with my fix, so I checked it into the test suite as well.
