### ISSUE TITLE
Initial value of arrays

### ISSUE THREAD

**Issue by RustanLeino** [Microsoft/dafny#84]
This feature request proposes two new ways to initialize array elements during allocation.  Both of these extend the syntax of array allocation with an optional expression in parentheses:

```
"new" TypeAndToken "[" Expressions "]" [ "(" Expression ")" ]
```

This change applies to production `Rhs` in `Dafny.atg`.  As long as there are no side effects in the right-hand side, Dafny allows `new` right-hand sides together with other right-hand sides (including other `new` right-hand sides).  This will also be allowed if one or more of those `new` expressions uses the new syntax.  (Note, a rule in Dafny is that if a `new` right-hand side allocates one object and calls its constructor, then--since the constructor may have a side effect--this must be the only right-hand side.  This rule is unaffected by the new syntax.)

The first new way gives one value that is to be used for every element of the array.  For any type `T`, list of expressions `nn`, and expression `D`, the type checker will for:

```
new T[nn](D)
```

check that `D` has type `T`.  The verifier will then use `D` as the initial value for all values of the array (where `D` is evaluated in the heap immediately before the allocation takes place).  The compiler will arrange to set the initial value of every array elements to `D` (computing `D` only once).

The second new way gives a function that says how to initialize the element at each index.  For any type `T` and expressions `n` and `F`, the type checker will for:

```
new T[n](F)
```

check that `F` has type `int -> T`.  The verifier will check that:

```
forall i :: 0 <= i < n ==> F.requires(i)
```

which makes sure that every index in the range `0..n` is in the domain of the function `F`.  (Here and below, the expression `F` is to be evaluated in the heap immediately before the array allocation takes place.)  Then, the verifier, and also the compiler, will arrange to make element `i` of the newly allocated array equal to `F(i)`.  The expression `F` is to be evaluated only once.

For array allocations of more than 1 dimension, the situation is similar.  I will describe it for 2-dimensional arrays here.  For any type `T` and expressions `m`, `n`, and `F`, the type checker will for:

```
new T[m,n](F)
```

check that `F` has type `(int, int) -> T`.  The verifier will check that:

```
forall i,j :: 0 <= i < m && 0 <= j < n ==> F.requires(i, j)
```

Then, the verifier and compiler will arrange to make element `i,j` of the newly allocated array equal to `F(i, j)`.  The expression `F` is to be evaluated only once.

There is one slightly tricky issue in the type checking of these new right-hand sides.  The tricky thing is to distinguish between the `D` case and the `F` case.  I think the best way would be in Dafny's type-inference implementation to add another constraint `C(T, k, E)`, which says that expression `E` either has type `T` or has type `(int^k) -> T`, where `k` is the dimensionality of the array and where I'm using the notation `(int^k) -> T` to denote a function from `k` integer arguments to type `T`.  Late in the type inference, if a `C` constraint has still not been resolved, then one could imagine letting the inference choose `T` as the type for `E`.

  Rustan

**Comment by layus** [comment]
More than this, what I am really missing are static initializers for arrays, just like `{1, 2, 3}` for sets and `[ 1 2 3]` for sequences. Maybe something like java's `new int[] {1, 2, 3}` ?

That being said, with your proposal we could probably do 
```
new int[3]( i -> [1, 2, 3][i] )
```

As for the ambiguity, it could be dropped by implementing only the second form and using lambdas.
```
new int[5, 10]( (i, j) -> 3)
