### ISSUE TITLE
How to install Dafny in ubuntu 16.04 LTS?

### ISSUE THREAD

**Issue by mhermo** [Microsoft/dafny#85]
I've tried to install Dafny in ubuntu. 
I wasn't able to run Dafny from  "Dafny 1.9.7 for Ubuntu"  in http://dafny.codeplex.com

Has anyone managed to do this successfully?  I'd really appreciate any help.
Montse

**Comment by parno** [comment]
I don't think the version on CodePlex is being actively maintained.  You may want to try the latest releases from GitHub (https://github.com/Microsoft/dafny/releases), and follow the installation instructions on the Wiki (https://github.com/Microsoft/dafny/wiki/INSTALL).

**Comment by mhermo** [comment]
Many thanks! I got it following the installation instructions on (https://github.com/Microsoft/dafny/wiki/INSTALL). However I have not yet managed to use Emacs as an IDE for Dafny (not so easy).

**Comment by parno** [comment]
Great, glad to hear it!

**Comment by mhermo** [comment]
Thank you very much. I am using Emacs 24.5.1, and according to "Dafny mode for emacs instruction" (from https://github.com/boogie-org/boogie-friends) I added the file  ~/.emacs.d/init.el containing what you say to setup MELPA. However, I am not able to find the boogie-friends package.

Attached you will find the packages I see when use M-x list-packages.  I don't know why "M-x package-refresh-contents" doesn't work.
[list-package.pdf](https://github.com/Microsoft/dafny/files/838054/list-package.pdf)

**Comment by cpitclaudel** [comment]
Sure :) Your problem is a MELPA issue, not directly related to Dafny.  See https://melpa.org/#/getting-started
