### ISSUE TITLE
Sequences easy property that is not verified

### ISSUE THREAD

**Issue by jiplucap** [Microsoft/dafny#87]
http://rise4fun.com/Dafny/qxg7F

**Comment by jaylorch** [comment]
Sequence slices are non-inclusive of the right index. So a sequence s isn't equal to s[0..|s|-1], but rather is equal to s[0..|s|]. Here's a fixed version, which doesn't even need the antecedent s != []:

method Test<T>() {
  assert forall s:seq<T> :: s == s[0..|s|];  
}

**Comment by jiplucap** [comment]
Uuuups, of course I knew that fact. I'm sorry for the cluelessness.
