### ISSUE TITLE
Dafny crash when assigning array synonym

### ISSUE THREAD

**Issue by layus** [Microsoft/dafny#88]
the following code crashes dafny. My investigations show that the array access is not handled correctly. Seems like a Grid cannot be indexed, and is not seen as a proper synonym for array2<int>.

```
type Grid = array2<int>

method Main() {
    var g: Grid := new int[9, 9];
    g[0, 0] := 1;
}
```

_using Dafny program verifier version 1.9.8.30829, Copyright (c) 2003-2016, Microsoft_

**Comment by layus** [comment]
Thanks @RustanLeino.

I believe there is a typo un the patch. In the test, the g[0,0] := ... is still commented out.

**Comment by RustanLeino** [comment]
Silly me.  Thanks for the bug reports, @layus.

  Rustan
