### ISSUE TITLE
Dafny crashes when using datatype constructor from another module

### ISSUE THREAD

**Issue by jaylorch** [Microsoft/dafny#89]
It seems that using a datatype constructor imported from another module causes Dafny to crash. Here's a short example where that constructor is GenericTypeModule.GenericTypeConstructor:

module GenericTypeModule
{
    datatype GenericType<T> = GenericTypeConstructor(t:T)
}

module SpecificTypeModule
{
    import GenericTypeModule

    datatype SubType = SubType()
    
    predicate Pred(s:GenericTypeModule.GenericType<SubType>, t:SubType)
    {
        s == GenericTypeModule.GenericTypeConstructor(t)
    }
}

**Comment by jaylorch** [comment]
For some reason, when I copied and pasted, I lost the <T> that's part of the code. There should be a <T> after GenericType in my example:

module GenericTypeModule
{
    datatype GenericType<T> = GenericTypeConstructor(t:T)
}

module SpecificTypeModule
{
    import GenericTypeModule
    
    datatype SubType = SubType()
    
    predicate Pred(s:GenericTypeModule.GenericType<SubType>, t:SubType)
    {
        s == GenericTypeModule.GenericTypeConstructor(t)
    }
}

**Comment by jaylorch** [comment]
For some reason, github deleted the <T> that's supposed to follow GenericType in my example. I'm attaching it as a file instead.

[err.dfy.txt](https://github.com/Microsoft/dafny/files/860145/err.dfy.txt)

**Comment by jaylorch** [comment]
Here's some more information:  The problem seems to be that SubType isn't visible in any of the scopes Dafny expects it to be visible in, the GenericTypeModule scope or the top-level scope. I can see why this would be a problem, but this should result in an error, not a crash.

For what it's worth, the fix to this error is to use:

abstract module GenericTypeModule
{
    type T
    datatype GenericType = GenericTypeConstructor(t:T)
}

module ConcreteTypeModule refines GenericTypeModule
{
    datatype SubType = SubType()
    type T = SubType
}

module UsingModule
{
    import ConcreteTypeModule
    
    predicate Pred(s:ConcreteTypeModule.GenericType, t:ConcreteTypeModule.SubType)
    {
        s == ConcreteTypeModule.GenericTypeConstructor(t)
    }
}

**Comment by qunyanm** [comment]
Can't repro. The test seems to run without crash or error.
