### ISSUE TITLE
Why Dafny cannot prove this?

### ISSUE THREAD

**Issue by jiplucap** [Microsoft/dafny#93]
method Test<T>(s:seq<T>) {
assert |set x | x in s| <= |s|;
}

**Comment by RustanLeino** [comment]
Several properties are needed to prove this.  It would of course be nice if Dafny could do it automatically, but my feeling is that this property will require a lemma.  Here is a lemma that proves the property:

```
method Test(s:seq) {
  SeqToSet(s);
  assert |set x | x in s| <= |s|;
}

lemma SeqToSet(s: seq)
  ensures |set x | x in s| <= |s|
{
  if s == [] {
  } else {
    var s' := s[1..];
    SeqToSet(s');
    assert (set x | x in s') + {s[0]} == (set x | x in s);
  }
}
```

  Rustan

**Comment by jiplucap** [comment]
Hi Rustan,
Thank you. The property is quite simple comparing with other that  
Dafny check automatically, isn't it?
Best,
Paqui
