### ISSUE TITLE
proofs by contradiction

### ISSUE THREAD

**Issue by jiplucap** [Microsoft/dafny#95]
I wonder if the following proof scheme is considered a "good" proof by Dafny

lemma L ( ... )
  requires P
  ensures Q
{
assume !Q;
...

assert !P;
}

In particular, does Dafny generate an executable file if the .dfy file contains an assume like above?

**Comment by RustanLeino** [comment]
What you have here is a proof by contradiction.  The entire body of the lemma is allowed to assume the precondition, `P`.  Then, you're essentially saying, "assume `Q` does not hold; I will then show you `!P`, which contradicts the precondition.  In fact, you could even follow the `assert !P;` with `assert false;` to make it even more clear that this is a proof by contradiction.  A proof by contradiction is a good proof.

However, the use of an `assume` is not a good idea. For example, if you accidentally copied `Q` incorrectly from the `ensures` clause, then you would not be proving what you think you're proving. Also, the compiler will not generate an executable if it sees an `assume` statement anywhere.

Here is the pattern I would suggest for a proof by contradiction:

```
lemma L(...)
  requires P
  ensures Q
{
  if !Q {
    ...
    assert !P;
    assert false;
  }
}
```

Here, if the "then" branch is taken, the proof eventually proves `!P`, which contradicts the `P` that the lemma is allowed to assume from the precondition.  Again, I like the `assert false;` at the end, to signal that you don't expect any control flow to ever get to that point in the lemma.  If the "else" branch is taken, then `Q` holds, so the postcondition follows.

  Rustan

**Comment by jiplucap** [comment]
Great, 
thank you, 
Paqui
